### ISSUE TITLE
Make go get-able

### ISSUE THREAD

**Issue by matrixik** [shurcooL/gtdo#19]
Hi,

Now when I try to go get gtdo and try to run it (for using with private programs) I'm getting errors:
```
2014/12/21 11:50:49 loadTemplates: html/template: pattern matches no files: `./assets/*.tmpl`
```
You can make it go get-able with https://github.com/GeertJohan/go.rice (check example folder, `go get github.com/GeertJohan/go.rice/example` and run example executable from `$GOPATH/bin` folder)

**Comment by shurcooL** [comment]
The situation should be better now, since #36 was merged.

I've also added instructions for installation and development to the README in 17f8d997816f0f3300808227081f3b7946591d7d.
