### ISSUE TITLE
Use of neelance/dom

### ISSUE THREAD

**Issue by neelance** [shurcooL/gtdo#32]
Hi Dmitri,

I guess you've already seen my experimental `neelance/dom` package. It's in a very early stage, but I'd like to improve it based on real-world use cases. That's why I would like to implement some parts of gotools.org with it. What do you think?

Cheers,
Richard

**Comment by shurcooL** [comment]
Hi Richard,

That's awesome! I'm glad you want to try to do that, and gtdo is open source to allow exactly that.

I am busy with some other things and can't spend as much time on this project at this time, but my next priority was going to be #11. Also, some of the code is messy and I haven't had a chance to clean it up yet. As long as you're okay with that.

Could you describe how you're imagining using `neelance/dom` in gtdo? I am somewhat familiar with the package, but it's not immediately obvious to me how it would fit in.

Thanks!

**Comment by shurcooL** [comment]
Also, some of the frontend parts of gtdo live in another repo, at [github.com/shurcooL/frontend](https://github.com/shurcooL/frontend). That's why it will be very helpful if you can describe what you want to try, so I can point you to the right places.

**Comment by neelance** [comment]
Not yet sure. Just wanted to ask first before looking into it. :-)

**Comment by shurcooL** [comment]
Sounds good. :) Let me know when you have any updates.

**Comment by shurcooL** [comment]
Since I believe this question is answered, I'll close this now. Feel free to reopen, create new issue, or just comment here if you have any updates on this.
