### ISSUE TITLE
does not build for me

### ISSUE THREAD

**Issue by gedw99** [shurcooL/gtdo#35]
```
gedw99-MacBook-Pro:gtdo apple$ go build
# github.com/shurcooL/gtdo
./main.go:399: not enough arguments in call to repo.Branches
./main.go:521: too many arguments in call to sg.Repository
./main.go:532: cannot use "sourcegraph.com/sourcegraph/go-vcs/vcs".RemoteOpts literal (type "sourcegraph.com/sourcegraph/go-vcs/vcs".RemoteOpts) as type *vcsclient.CloneInfo in argument to repo.(vcsclient.RepositoryCloneUpdater).CloneOrUpdate
gedw99-MacBook-Pro:gtdo apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/Workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/Workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
gedw99-MacBook-Pro:gtdo apple$ go version
go version go1.5beta3 darwin/amd64
gedw99-MacBook-Pro:gtdo apple$ 
```

**Comment by shurcooL** [comment]
Hi @gedw99,

This project currently uses [`godep`](https://github.com/tools/godep) tool for builds, so you need to use it. Once you install it, try this command:

```
godep go build
```

**Comment by shurcooL** [comment]
I've pushed a new version, and added instructions for installation and development to the README in 17f8d997816f0f3300808227081f3b7946591d7d.

**Comment by gedw99** [comment]
hey. yep i just saw it. will try it

**Comment by gedw99** [comment]
when i do a go get i am getting quite a few errors.
i am on go 1.5 beta3.

are you getting these ?

go get -u github.com/shurcooL/gtdo
# github.com/shurcooL/gtdo
./main.go:384: not enough arguments in call to repo.Branches
./main.go:506: too many arguments in call to sg.Repository
./main.go:517: cannot use "sourcegraph.com/sourcegraph/go-vcs/vcs".RemoteOpts literal (type "sourcegraph.com/sourcegraph/go-vcs/vcs".RemoteOpts) as type *vcsclient.CloneInfo in argument to repo.(vcsclient.RepositoryCloneUpdater).CloneOrUpdate

**Comment by gedw99** [comment]
Ok i followed the instruction and it worked.
Very complex project...
what localhost port does it use ?

**Comment by shurcooL** [comment]
Try running:

```
gtdo -help
```

That should print the flags it accepts. One of the flags is `http` and controls the address being served. The default value for that flag is ":8080", which means to serve on all interfaces on port 8080.

**Comment by gedw99** [comment]
ok yep it works thanks.

a bit no golang :) but amazing app still.

i really like it, and hope that the build / deploy process gets make a bit more golang like..

**Comment by shurcooL** [comment]
Thanks. I plan to improve it so it's completely go gettable without needing `godep`, but it might take some time. Issue #19 is open to track progress.

**Comment by gedw99** [comment]
for note:
from all the versioning systems i looked at godep seemed to be a reality of being needed for non library.
But since this code ues so many other projects godep is the best we have right now ?

**Comment by shurcooL** [comment]
I am considering Go 1.5 vendor experiment (`GO15VENDOREXPERIMENT=1`) approach, but I am not happy with some issues it suffers from at this time, so I'll continue to rely on `godep` until I get to a better alternative.
