### ISSUE TITLE
Poor rendering in Firefox.

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/gtdo#41]
This URL https://gotools.org/github.com/shurcooL/go/gists/gist7480523?rev=a84e97085eb0de48f81e98e00b1d7e6697f3875d#main-go-L101-L110 renders correctly in Chrome:

![image](https://cloud.githubusercontent.com/assets/1924134/12004957/b2d79dee-ab38-11e5-912d-78088d9b8329.png)

But not so in Firefox:

![image](https://cloud.githubusercontent.com/assets/1924134/12004958/ba46cbfe-ab38-11e5-9b8f-4814fba26b8a.png)

Thanks @dominikh for reporting.

**Comment by shurcooL** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size, Firefox needs a "-moz-" prefix for tab-size CSS property. Doing that is one part of the fix. But there's more.

**Comment by shurcooL** [comment]
@dominikh, this issue should be resolved now, and the new version is deployed. Please let me know if it's not working for you.

**Comment by dominikh** [comment]
It's working fine now.

**Comment by shurcooL** [comment]
Great!
