### ISSUE TITLE
Repos without master branch fail to display.

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/gtdo#42]
This is a bug that should be fixed.

E.g., currently happening with:

https://gotools.org/github.com/kr/text

![image](https://cloud.githubusercontent.com/assets/1924134/15095511/25598158-147e-11e6-9d5a-f36428579831.png)

This is related to https://github.com/golang/go/issues/9032 and https://github.com/golang/gddo/issues/405.

**Comment by shurcooL** [comment]
I've resolved this in https://github.com/shurcooL/gtdo/commit/ae7ecb7b1c847b6a25f687916616aa7c342e0768, which builds on work done in https://github.com/shurcooL/vcsstate/commit/c4807b9e56e742ce687ca75af724b56e468d5699.

Unfortunately, in order to reliably support branches other than "master" as default branches, an additional network call must be made.

**Comment by kr** [comment]
That's too bad it needs an extra network call. Note that if you clone a git repo, the default branch is available as `remotes/origin/HEAD`. Maybe that would help?

```
$ git clone https://github.com/kr/text
...
$ cd text/
$ git branch -va
* main                7cafcd8 cmd/agg: new command
  remotes/origin/HEAD -> origin/main
  remotes/origin/cb   0a50dc0 add test from #4
  remotes/origin/main 7cafcd8 cmd/agg: new command
  remotes/origin/wip  67253a9 wip
```

**Comment by kr** [comment]
Also, thanks! This is great. :)

**Comment by shurcooL** [comment]
> That's too bad it needs an extra network call. Note that if you clone a git repo, the default branch is available as `remotes/origin/HEAD`. Maybe that would help?

Thanks. I am aware of that, and I tried to use that initially. You can see some of those left-over experiments [here](https://github.com/shurcooL/vcsstate/commit/c4807b9e56e742ce687ca75af724b56e468d5699#diff-b112433c20987b983fa33aa1eac9482dR205).

However, I cannot rely on that for a few reasons:

1. It's not guaranteed to be up to date. So a network call must be made in a general case. For example, imagine a worst case where the upstream repository changes its default branch from `master` to `another-branch`, and a minute later someone tries to view that repo. Unless you make a network call to query the latest current default branch, you may end up having stale, inaccurate default branch information.

2. The symbolic ref to remotes/origin/HEAD may or may not exist. It depends on how the repo was cloned, what version of git was used, and some other factors. Also, users can do `git remote set-head origin -d` which will remove that symbolic ref. You can try to restore it with `git remote set-head origin --auto`, but that has gotchas:

    > With `-a` or `--auto`, the remote is queried to determine its `HEAD`, then the symbolic-ref `refs/remotes/<name>/HEAD` is set to the same branch. e.g., if the remote `HEAD` is pointed at `next`, `"git remote set-head origin -a"` will set the symbolic-ref `refs/remotes/origin/HEAD` to `refs/remotes/origin/next`. This will only work if `refs/remotes/origin/next` already exists; if not it must be fetched first.
