### ISSUE TITLE
Importers tab is failing to display any importers.

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/gtdo#43]
Originally reported [on Twitter](https://twitter.com/andychilton/status/811366523491094528) by @chilts.

This page is currently showing "None" for importers:

https://gotools.org/github.com/boltdb/bolt?tab=importers

![image](https://cloud.githubusercontent.com/assets/1924134/21373769/612746e2-c6ef-11e6-9220-0de6c08adc4f.png)

But there are many importers (https://godoc.org/github.com/boltdb/bolt?importers).

It's happening because of a failure trying to access the godoc.org API.

The error is in the server log:

```
2016/12/20 19:28:21 Get https://api.godoc.org/importers/github.com/boltdb/bolt: x509: certificate signed by unknown authority
```

I've filed https://github.com/golang/gddo/issues/462, once there's a resolution for that, this should be easy to fix.

**Comment by shurcooL** [comment]
This was an external issue with the godoc.org API, which has [been resolved](https://github.com/golang/gddo/issues/462#issuecomment-268409821).

https://gotools.org/github.com/boltdb/bolt?tab=importers displays all importers as expected now.

![image](https://cloud.githubusercontent.com/assets/1924134/21374984/7bff55b4-c6f8-11e6-9165-2f214cae9811.png)

**Comment by chilts** [comment]
Thanks @shurcooL and @stephenmw  for fixing https://github.com/golang/gddo/issues/462. :)
