### ISSUE TITLE
Use /vendors

### ISSUE THREAD

**Issue by Eun** [shurcooL/gtdo#52]
You should really provide a `vendors` directory.
I am not able to `go get` the project:

```
./main.go:526:6: cannot use NewPrefixFS(fs, "/virtual-go-workspace") (type *prefixFileSystem) as type vfs.FileSystem in assignment:
	*prefixFileSystem does not implement vfs.FileSystem (missing RootType method)
./main.go:528:6: cannot use NewPrefixFS(fs, "/virtual-go-workspace/src/" + repoImportPath) (type *prefixFileSystem) as type vfs.FileSystem in assignment:
	*prefixFileSystem does not implement vfs.FileSystem (missing RootType method)
```

**Comment by shurcooL** [comment]
Thanks for reporting. I've fixed this issue locally, but haven't pushed it yet. Will do so now.

I don't plan on using the `vendor` directory, this project is expected to build with the latest versions of dependencies.

(As a heads up, the code quality of this project is unfortunately very low. It was created a long time ago as a quick prototype, and I haven't had a chance to rewrite it properly as it deserves.)
