### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by inliquid** [shurcooL/gtdo#57]
Hi, having issues with `gotools.org` for a couple of days with different projects, f.e.
https://gotools.org/gorilla/mux
![изображение](https://user-images.githubusercontent.com/6797881/70608919-02315d00-1c12-11ea-86bf-a761296cbfd0.png)

**Comment by inliquid** [comment]
Just realized that with `github.com` at the beginning of path it works... Not sure if there were any changes, I thought I was accessing like the above example, by replacing `github.com` with `gotools.org`, but I might be messing up something... Should close this probably.

**Comment by dmitshur** [comment]
@inliquid There haven’t been any changes on gotools.org recently.

The URL design has always been `https://gotools.org/<full import path>`, so yes, the right URL for mux is https://gotools.org/github.com/gorilla/mux.

If you do https://gotools.org/gorilla/mux, it looks for a package with the import path `gorilla/mux`, which doesn’t exist.

Perhaps you were thinking of the standard library packages? Those don’t have a `github.com` prefix. E.g., to view code for `encoding/json`, the URL is https://gotools.org/encoding/json.

**Comment by inliquid** [comment]
@dmitshur maybe, I just didn't use the tool for a while and probably forgot it. Thank you.
