### ISSUE TITLE
zoekt integration

### ISSUE THREAD

**Issue by x0rzkov** [shurcooL/gtdo#58]
Hi,

Hope you are all well !

I was wondering how it could be to integrate zoekt (https://github.com/google/zoekt) trigram search engine to gtdo. How would you proceed ? 

If you give me some hints, I can try to fork gtdo and do it.

Cheers,
X

**Comment by dmitshur** [comment]
Hello.

This is a very complicated question. I can't give a good answer without spending time on researching and thinking about this.

The current scope of gtdo is to display Go package source code in a browser on one page, and rely on browser's built-in search. Any kind of search beyond that is out of scope, so I haven't thought about it. There are other projects that try to tackle code search.

Hope this helps.
